# Generated by Django 4.1.5 on 2023-02-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_is_lecturer_remove_user_is_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (3, 'Lecturer'), (2, 'Student')], default=1, verbose_name='User Types'),
        ),
    ]
