# Generated by Django 4.1.5 on 2023-02-10 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_course_timeperiod_user_course_students'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
