# Generated by Django 4.1.5 on 2023-02-10 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_students_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='programs and course',
        ),
    ]
