# Generated by Django 4.1.5 on 2023-02-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_user_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeperiod',
            name='end_year',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='timeperiod',
            name='start_year',
            field=models.DateField(),
        ),
    ]
