# Generated by Django 4.1.5 on 2023-02-24 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_program_remove_course_course_name_course_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programs and course',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.program'),
        ),
    ]
