# Generated by Django 4.1.5 on 2023-02-24 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_remove_course_level_remove_course_program_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_name',
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Bachelor', 'Bachelor Degree'), ('Master', 'Master Degree')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.program'),
        ),
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
