# Generated by Django 4.1.5 on 2023-01-26 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_coursedetails_hoddetails_staffdetails_studentdetails_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursedetails',
            old_name='gda_id',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='hoddetails',
            old_name='gda_id',
            new_name='hod_id',
        ),
        migrations.RenameField(
            model_name='staffdetails',
            old_name='gda_id',
            new_name='staff_id',
        ),
        migrations.RenameField(
            model_name='studentdetails',
            old_name='gda_id',
            new_name='student_id',
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='course_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.coursedetails'),
        ),
    ]
