# Generated by Django 4.1.5 on 2023-01-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_rename_gda_id_coursedetails_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetails',
            name='course_id',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='course_id'),
        ),
        migrations.AlterField(
            model_name='hoddetails',
            name='hod_id',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='hod_id'),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='staff_id',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='staff_id'),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='student_id',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='student_id'),
        ),
    ]
