# Generated by Django 4.1.5 on 2023-01-26 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_coursedetails_course_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(blank=True, max_length=200, unique=True, verbose_name='student_id')),
                ('subject_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.coursedetails')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.staffdetails')),
            ],
            options={
                'verbose_name': 'Subject',
            },
        ),
    ]
